# frozen_string_literal: true

module Diffdash
  module Services
    # Posts comments to GitHub PRs with dashboard links
    class PrCommenter
      COMMENT_MARKER = "<!-- diffdash-dashboard -->"

      def initialize(verbose: false)
        @verbose = verbose
      end

      # Post or update a comment on the current PR with the dashboard link
      # @param dashboard_url [String] URL to the Grafana dashboard
      # @return [Boolean] true if comment was posted, false otherwise
      def post(dashboard_url:)
        return false unless github_pr_context?
        return false unless gh_cli_available?

        pr_number = current_pr_number
        return false unless pr_number

        comment_body = build_comment(dashboard_url)

        # Check if we already have a diffdash comment
        existing_comment_id = find_existing_comment(pr_number)

        if existing_comment_id
          update_comment(existing_comment_id, comment_body)
        else
          create_comment(pr_number, comment_body)
        end

        true
      rescue StandardError => e
        log_verbose("Failed to post PR comment: #{e.message}")
        false
      end

      private

      def github_pr_context?
        ENV["GITHUB_ACTIONS"] == "true" && ENV["GITHUB_EVENT_NAME"] == "pull_request"
      end

      def gh_cli_available?
        system("which gh > /dev/null 2>&1")
      end

      def current_pr_number
        # In GitHub Actions, we can get PR number from GITHUB_REF or GITHUB_EVENT_PATH
        if ENV["GITHUB_REF"]&.match?(%r{refs/pull/(\d+)/merge})
          return ENV["GITHUB_REF"].match(%r{refs/pull/(\d+)/merge})[1]
        end

        # Fallback: try to get from gh cli
        result = `gh pr view --json number -q '.number' 2>/dev/null`.strip
        result.empty? ? nil : result
      end

      def find_existing_comment(pr_number)
        # List comments and find one with our marker
        result = `gh pr view #{pr_number} --json comments -q '.comments[] | select(.body | contains("#{COMMENT_MARKER}")) | .id' 2>/dev/null`.strip
        result.empty? ? nil : result.split("\n").first
      end

      def create_comment(pr_number, body)
        log_verbose("Creating PR comment on ##{pr_number}")
        system("gh", "pr", "comment", pr_number, "--body", body)
      end

      def update_comment(comment_id, body)
        log_verbose("Updating existing PR comment #{comment_id}")
        system("gh", "api", "-X", "PATCH", "/repos/{owner}/{repo}/issues/comments/#{comment_id}", "-f", "body=#{body}")
      end

      def build_comment(dashboard_url)
        <<~COMMENT
          #{COMMENT_MARKER}
          ## 📊 Diffdash Dashboard

          A Grafana dashboard has been created for this PR's observability signals.

          **[View Dashboard](#{dashboard_url})**

          ---
          <sub>Auto-generated by [diffdash](https://github.com/rossme/diffdash) v#{VERSION}</sub>
        COMMENT
      end

      def log_verbose(message)
        warn "[diffdash] #{message}" if @verbose
      end
    end
  end
end
