# frozen_string_literal: true

module Grafantastic
  module Dashboard
    class Builder
      def initialize(title:, signals:, config:)
        @title = title
        @signals = signals
        @config = config
      end

      def build
        {
          dashboard: build_dashboard,
          folderId: @config.grafana_folder_id&.to_i,
          overwrite: true,
          message: "Auto-generated by grafantastic gem"
        }
      end

      private

      def build_dashboard
        {
          id: nil,
          uid: generate_uid,
          title: @title,
          tags: %w[auto-pr grafantastic],
          timezone: "browser",
          schemaVersion: 39,
          version: 0,
          refresh: "30s",
          time: {
            from: "now-1h",
            to: "now"
          },
          templating: build_templating,
          panels: build_panels,
          annotations: {
            list: [
              {
                name: "Deployments",
                datasource: { type: "prometheus", uid: "${datasource}" },
                enable: true,
                expr: "changes(deploy_timestamp{service=\"$service\"}[5m]) > 0",
                tagKeys: "service",
                titleFormat: "Deploy"
              }
            ]
          }
        }
      end

      def generate_uid
        # Deterministic UID based on title
        Digest::SHA256.hexdigest(@title)[0, 12]
      end

      def build_templating
        {
          list: [
            {
              name: "datasource",
              type: "datasource",
              query: "prometheus",
              current: {},
              hide: 0
            },
            {
              name: "datasource_loki",
              type: "datasource",
              query: "loki",
              current: {},
              hide: 0
            },
            {
              name: "service",
              type: "query",
              datasource: { type: "prometheus", uid: "${datasource}" },
              query: "label_values(up, service)",
              refresh: 2,
              includeAll: false,
              multi: false
            },
            {
              name: "env",
              type: "custom",
              query: "production,staging,development",
              current: { text: "production", value: "production" },
              includeAll: false,
              multi: false
            }
          ]
        }
      end

      def build_panels
        return [PanelTemplates.empty_dashboard_panel] if @signals.empty?

        panels = []
        panel_id = 1
        current_y = 0

        logs = @signals.select(&:log?)
        metrics = @signals.select(&:metric?)

        # Add log panels
        logs.each_with_index do |signal, idx|
          grid_pos = { x: (idx % 2) * 12, y: current_y + (idx / 2) * 8, w: 12, h: 8 }
          panels << PanelTemplates.log_panel(signal, panel_id, grid_pos)
          panel_id += 1
        end

        current_y += ((logs.size + 1) / 2) * 8 if logs.any?

        # Add metric panels
        metrics.each_with_index do |signal, idx|
          grid_pos = { x: (idx % 3) * 8, y: current_y + (idx / 3) * 8, w: 8, h: 8 }

          case signal.metadata[:metric_type]
          when :histogram
            histogram_panels = PanelTemplates.histogram_panels(signal, panel_id, grid_pos)
            panels.concat(histogram_panels)
            panel_id += histogram_panels.size
          when :gauge
            panels << PanelTemplates.gauge_panel(signal, panel_id, grid_pos)
            panel_id += 1
          else
            panels << PanelTemplates.counter_panel(signal, panel_id, grid_pos)
            panel_id += 1
          end
        end

        panels
      end
    end
  end
end
